### PR TITLE
Moves finance DSL to separate subproject

### PR DESCRIPTION
**Pull request by jqno**

### CODE REVIEW

**Comment by jhkuperus** [comment]
👍

**Comment by vzorge** [comment]
Looks good. We will have to plan when to integrate this into a release, because it will break dependencies hard. We may need to have a release first before merging this back

**Comment by jqno** [comment]
Good point, didn't think of that. Any chance of doing that before Wednesday? :wink:

**Comment by jqno** [comment]
I guess my proposal of renaming NumberLike to Quantity might also break some things in the dependencies. If everybody agrees with that rename, we could do that together with this one and have one majorly breaking version, instead of two smaller ones :smile:

**Comment by jhkuperus** [comment]
What do we need the release for? The list filter? If so, let's merge that in, release and then build a release with these changes.

**Comment by jhkuperus** [comment]
PR updated with 0.2.3 changes. @jqno please check if everything is still as intended.

**Comment by jqno** [comment]
@jhkuperus Out of curiosity: what was the reason for extracting the FinanceDsl trait out from the package object?

Other than that, I say :ship: !

**Comment by jhkuperus** [comment]
Well, importing a package object is fantastic if it gives you all the implicits and features you need. However, if you feel the need to extend the original DSL with let's say a `.yen` conversion, there is no easy way to let your aggregate package object extend the one from the finance DSL.

In comes the `FinanceDsl`-trait. If you need to extend the DSL to fit your needs, include all of its implicit definitions in your DSL by simply extending the `FinanceDsl` trait.

(We ran into this with the `ScalaRulesDsl`, which we extend heavily now that its base resides in this repository)

**Comment by jqno** [comment]
OK, good point! Hadn't thought of that.

I was a little confused because it appeared in a merge commit, so I wasn't sure if it was intentional or not.

In retrospect, I suppose this was the conflict you were talking about :).

**Comment by jqno** [comment]
Also, yay for merging! ;)

**Comment by jhkuperus** [comment]
Yep, that was the conflict :) We had introduced that trait, but Git had annotated it as a move, which conflicted with your move .. 🐳

**Comment by jqno** [comment]
Mystery solved! :tada:

**Pull request merged**
