### PR TITLE
#16 is method refactoring

### PR DESCRIPTION
**Pull request by vzorge**

### CODE REVIEW

**Comment by vzorge** [comment]
@NRBPerdijk @jhkuperus  Could you look at this?

**Comment by jhkuperus** [comment]
👍  approved :)

**Comment by jhkuperus** [comment]
Check [Branching](https://github.com/scala-rules/scala-rules/wiki/Branching) for a proposal on branch naming. Share your thoughts!

**Comment by vzorge** [comment]
Goed idee van de branchnamen

**Comment by vzorge** [comment]
@NRBPerdijk Can I merge this back?

**Pull request merged**
